### ISSUE TITLE
twocents & realblog

### ISSUE THREAD

**Issue by frase-git** [cmb69/twocents_xh#23]
Habe gerade twocents-master mit realblog-master zusammen versucht.
Keine Kommentare angezeigt und keine Möglichkeit Kommentare zu schreiben.
?
Geht das im Moment noch nicht?

**Comment by cmb69** [comment]
Hm. ich habe kürzlich bei beiden Plugins etwas umgestellt, so dass etwas ältere Versionen des einen mit einer ganz aktuellen Version des anderen nicht funktionieren sollten. Ganz aktuelle master müssten aber wieder zusammen passen.

Bitte überprüfe also, ob Du wirklich die ganz aktuellen master von beiden Plugins hast.

**Comment by frase-git** [comment]
> Bitte überprüfe also, ob Du wirklich die ganz aktuellen master von beiden Plugins hast.

Aua. Das geht ja schnell hier ;-)
Mein Blog war schon ein paar Tage älter.
Mit neu geht's.
Sorry, für die Störung.

**Comment by cmb69** [comment]
> Sorry, für die Störung.

Kein Problem! Im Gegenteil: ich ja froh über Tester und deren Feedback, und zumindest hier weiß ich nun, dass es nicht nur bei mir lokal funktioniert. :)
