### ISSUE TITLE
Add comments heading

### ISSUE THREAD

**Issue by frase-git** [cmb69/twocents_xh#24]
Das hast du nun davon ...

Ich wünsche mir einen Header über den Kommentaren (Sprachvariable).
Siehe Testseite.

**Comment by cmb69** [comment]
> Ich wünsche mir einen Header über den Kommentaren (Sprachvariable).

Ja, das sollte sein. Allerdings würde ich das eigentlich eher beim Realblog machen; wird Twocents_XH standalone eingesetzt, dann ist der Header nicht unbedingt sinnvoll, und kann ja auch vom Webmaster auf der Seite manuell gesetzt werden.

Oder übersehe ich etwas?

**Comment by frase-git** [comment]
> Oder übersehe ich etwas?

Meistens übersiehst du die Sachen besser als ich.
Theoretisch könne man auch im Blog die Ü setzen.
Aber, warum nicht auch optional für standalone-2Cents?
Vielleicht: wenn leer, dann nicht ? - Im Falle einer Sprachvariable.
Oder in der Konfig wählbar: Ü: ja/nein

**Comment by cmb69** [comment]
> Theoretisch könne man auch im Blog die Ü setzen.
Aber, warum nicht auch optional für standalone-2Cents?

Hm, im Blog sind sie erforderlich, im standalone Betrieb nicht unbedingt. Der entscheindende Punkt ist wohl wie andere Kommentarplugins das handhaben würden (ja, ich weiß, es gibt noch keine, aber ich hoffe doch sehr, dass Alternativen angeboten werden, weil Twocents_XH sicher nicht jedermanns Sache ist, und ich auch nicht allzu viel Zeit in das Plugin investieren möchte). Letzlich ist das aber wohl etwas, was ich einfach dokumentieren sollte.

Mir gefällt die Überschrift im Blog aber mehr, da dann das Kommentarplugin auch zusätzlich leichter als Gästebuch eingesetzt werden kann, wo die Überschrift "Kommentare" vermutlich nicht ganz so passend wäre.

**Comment by frase-git** [comment]
Bin mit allem einverstanden ...

**Comment by cmb69** [comment]
> Bin mit allem einverstanden ...

Ich aber nicht. :) Ich habe noch mal drüber nachgedacht, und mir alternative Kommentarplugins vorgestellt. Eine durchaus denkbare Variante könnte das Hinzufügen eines neuen Kommentars mit einem eigenen Formular erledigen, das dann sinnvollerweise die Überschrift "Neuen Kommentar hinzufügen" o.ä. haben könnte. Wenn dann der Realblog oberhalb dieser Überschrift noch "Kommentare" ausgibt, ist das irgendwie Quatsch.

Am besten ist wohl, diese Überschrift von der jeweiligen `CommentsBridge::handle()` Implementierung (hier also `RealblogBridge::handle()`) erledigen zu lassen, die ja nicht unbedingt nur den eigentlichen Rückgabewert des Pluginaufrufs (wie bisher) liefern muss, sondern halt noch eine passende Überschrift dazu. Wird `twocents()` direkt aufgerufen, dann bleibt trotzdem alles beim alten.
