### ISSUE TITLE
Links in user comments should have rel=nofollow

### ISSUE THREAD

**Issue by cmb69** [cmb69/twocents_xh#26]
This is rather mandatory to mitigate spam. See also https://support.google.com/webmasters/answer/96569?hl=en.

**Comment by cmb69** [comment]
Actually, this is already supposed to be the case, see http://3-magi.net/demo/interaction/de/?Twocents_XH#twocents_comment_53dc793d8ed0b, but somehow it doesn't seem to work for localhost (an issue in HTMLPurifier?).

**Comment by frase-git** [comment]
Jetzt bin ich aber verwirrt. Das hat doch schonmal funktioniert.
In der aktuellen Version funktioniert es nicht mehr.
Siehe Testseite (dein Zugang ist aktiv).

**Comment by cmb69** [comment]
> In der aktuellen Version funktioniert es nicht mehr.

Da habe ich diesbezüglich wissentlich nichts geändert, außer dass ich den HTMLPurifier aktualisiert habe. Mit der vorigen Version schien es local aber auch nicht zu funktionieren. Muss ich mir genauer anschauen. Danke auf jeden Fall für den Online-Test.

> Schau dir mal die Editorbuttons an. Alles nur per CSS gemacht.

Ja, sehr schön. Die vorherigen haben mir sogar noch besser gefallen, aber das geht wohl wegen dem State-Tracking nicht mehr.

**Comment by cmb69** [comment]
Ich bin ein Trottel! Das rel=nofollow wird wie gewünscht eingefügt, aber eben nur, wenn der Post nicht vom Admin gemacht wurde! Nur Posts von Besuchern werden überhaupt bereinigt. Der Webmaster wird schon nichts verlinken, dem nicht gefolgt werden soll (außer er will seine eigene Website vollspammen).

**Comment by frase-git** [comment]
> Ich bin ein Trottel!

Na ich erst ;-)
Klappt alles bestens!

**Comment by cmb69** [comment]
> Na ich erst ;-)

Du hast es wenigstens nicht programmiert. :)

> Klappt alles bestens!

Danke für die Rückmeldung!
