### ISSUE TITLE
pagination error

### ISSUE THREAD

**Issue by frase-git** [cmb69/twocents_xh#36]
Bei Überschreiten von pagination_max folgt:

> Fatal error: Call to undefined function xdebug_break() in ... \plugins\twocents\views\pagination.php on line 4

**Comment by frase-git** [comment]
Entferne Zeile 4:
`<?php xdebug_break()?>`
dann scheint es zu gehen.

**Comment by cmb69** [comment]
Hm, das hatte ich unmittelbar vor dem Release von 1.0beta1 [gefixt](https://github.com/cmb69/twocents_xh/commit/2ec26632e97da094abed4ed0038082645f2e3199); allerdings erst nachdem ich 1.0beta1 getaggt hatte, so dass ich den Tag löschen und neu setzen musste. Evtl. hast Du die Version nach dem ersten Taggen erwischt? Bitte mal prüfen.

**Comment by frase-git** [comment]
Ich habe es heute morgen auf deiner HP runtergeladen.
da ist die Zeile drin. ?

**Comment by cmb69** [comment]
> Ich habe es heute morgen auf deiner HP runtergeladen.
da ist die Zeile drin. ?

Mist – da habe ich wohl die korrigierte 1.0beta1 nicht mehr hochgeladen. Das habe ich nun nachgeholt. Ärgerlich ist, dass nun zwei verschiedene 1.0beta1 im Umlauf sind. Gab aber nur eine handvoll Downloads bisher – damit wird man leben müssen.
