### ISSUE TITLE
Archiv-Funktion

### ISSUE THREAD

**Issue by Berni-MD** [cmb69/twocents_xh#64]
Es wäre toll, wenn das Plugin eine Funktion zur Verfügung stellen würde die es ermöglicht alle bisherigen Eintragungen einzublenden OHNE das hier neue Eintragungen dazu kommen können.

Sprich der Button:  "Neuen Kommentar verfassen" einfach nicht mehr mit einblenden.

**Comment by cmb69** [comment]
Das hatte ich schon 2017 umgesetzt (#18), aber noch immer keine neue Version veröffentlicht. Wird hoffentlich sehr bald kommen.
